### ISSUE TITLE
Site break after gulp copy-deps

### ISSUE THREAD

**Issue by leighghunt** [leighghunt/aspnetcoreangular2#5]
After ```gulp copy-deps``` in , get the following errors in browser:

```
Rx.min.js:24 Uncaught TypeError: __extends is not a function(…)(anonymous function) @ Rx.min.js:24(anonymous function) @ Rx.min.js:24(anonymous function) @ Rx.min.js:10(anonymous function) @ Rx.min.js:10
core.umd.js:2837 EXCEPTION: viewUtils.createRenderComponentType is not a functionErrorHandler.handleError @ core.umd.js:2837(anonymous function) @ core.umd.js:6361e.invoke @ zone.min.js:1onInvoke @ core.umd.js:5975e.invoke @ zone.min.js:1n.run @ zone.min.js:1(anonymous function) @ zone.min.js:1e.invokeTask @ zone.min.js:1onInvokeTask @ core.umd.js:5966e.invokeTask @ zone.min.js:1n.runTask @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1
core.umd.js:2842 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:2842(anonymous function) @ core.umd.js:6361e.invoke @ zone.min.js:1onInvoke @ core.umd.js:5975e.invoke @ zone.min.js:1n.run @ zone.min.js:1(anonymous function) @ zone.min.js:1e.invokeTask @ zone.min.js:1onInvokeTask @ core.umd.js:5966e.invokeTask @ zone.min.js:1n.runTask @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1
core.umd.js:2843 TypeError: viewUtils.createRenderComponentType is not a function
    at viewFactory_AppComponent_Host0 (AppComponent_Host.ngfactory.js:28:92)
    at new CompiledTemplate.proxyViewFactory (http://localhost:5001/lib/npmlibs/@angular/compiler/bundles/compiler.umd.js:16996:41)
    at ComponentFactory.create (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:5480:28)
    at ApplicationRef_.bootstrap (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6550:44)
    at eval (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6459:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6459:46)
    at eval (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6427:31)
    at e.invoke (http://localhost:5001/lib/npmlibs/zone.js/zone.min.js:1:14497)
    at Object.onInvoke (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:5975:41)ErrorHandler.handleError @ core.umd.js:2843(anonymous function) @ core.umd.js:6361e.invoke @ zone.min.js:1onInvoke @ core.umd.js:5975e.invoke @ zone.min.js:1n.run @ zone.min.js:1(anonymous function) @ zone.min.js:1e.invokeTask @ zone.min.js:1onInvokeTask @ core.umd.js:5966e.invokeTask @ zone.min.js:1n.runTask @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1
zone.min.js:1 Unhandled Promise rejection: viewUtils.createRenderComponentType is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: viewUtils.createRenderComponentType is not a function(…) TypeError: viewUtils.createRenderComponentType is not a function
    at viewFactory_AppComponent_Host0 (AppComponent_Host.ngfactory.js:28:92)
    at new CompiledTemplate.proxyViewFactory (http://localhost:5001/lib/npmlibs/@angular/compiler/bundles/compiler.umd.js:16996:41)
    at ComponentFactory.create (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:5480:28)
    at ApplicationRef_.bootstrap (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6550:44)
    at eval (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6459:93)
    at Array.forEach (native)
    at PlatformRef_._moduleDoBootstrap (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6459:46)
    at eval (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:6427:31)
    at e.invoke (http://localhost:5001/lib/npmlibs/zone.js/zone.min.js:1:14497)
    at Object.onInvoke (http://localhost:5001/lib/npmlibs/@angular/core/bundles/core.umd.js:5975:41)o @ zone.min.js:1a @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1
zone.min.js:1 Error: Uncaught (in promise): TypeError: viewUtils.createRenderComponentType is not a function(…)o @ zone.min.js:1a @ zone.min.js:1a @ zone.min.js:1invoke @ zone.min.js:1
```

**Comment by leighghunt** [comment]
Fairly sure this is due to angular (either part or all) being updated form 2.0.0 to 2.2.3, owing to semver differences in ```package.json``` resolving to difference versions:

```
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "^2.0.0",
    "@angular/forms": "^2.0.0",
    ...
    ...
```

**Comment by leighghunt** [comment]
This may have been what made it work in the first place - I copied the files manually. 0081321962d340030c9554d171542ff8fa48c608
